### ISSUE TITLE
vehicle_types_available in all/station_status.json uses wrong format

### ISSUE THREAD

**Issue by vkrause** [bbnavi/moqo2gbfs#7]
The form-factor filtered feeds have this in the correct format:
```
        "vehicle_types_available": [
          {
            "vehicle_type_id": "Renault ZOE 360km",
            "count": 1
          }
        ],
```

while in the "all" feed it looks like this:
```
        "vehicle_types_available": {
          "Renault ZOE 360km": 1
        },
```

Ie. `update_availability_status` would need the same logic as `station_with_available_vehicles_array` in moqoToGBFS.py, but that's slightly more than I can reasonably do blindly without a way to test this :)

**Comment by derhuerst** [comment]
related: @hbruch Would it be possible to check MOQO API responses into this repo, to have something like an integration test? This would make it much easier for others to contribute.
